### ISSUE TITLE
Don's sign the download path

### ISSUE THREAD

**Issue by lincoo2436** [jun7/wyeb#20]
Wyeb is the good vim like web-browser. I just want to know how I can download files which don't sign save path.
Thank you.

**Comment by jun7** [comment]
Thank you for reporting.
Sorry what means the 'files which don't sign save path' ?
I can't get what you are saying well though
wyeb uses XDG_DOWNLOAD_DIR + / + dlsubdir(of the conf).
Basically, wyeb throws file management to filers. wyeb does only save the files to the XDG's dir because I think the save dialogs what other browsers have nerver be  useful as filers.
Though there is download window's entry for long downloading.

**Comment by lincoo2436** [comment]
Sorry for the poor description of "files which don't sign save path",I'm not an English native speaker.So you know.But you have answer my question.I used to using the save dialogs,but wyeb can't do that . So,I try to ask the question,thank you for reply.

**Comment by jun7** [comment]
So then there is more infomation.
shift + d shows download dir and you can switch dlsubdir by use of set:* or uri:* of the conf.

BTW
I don't care whether native or not because I can't recognize it ;P
Therefore please feel free to report with it.
Thank you!

**Comment by lincoo2436** [comment]
Thank you ~
I get the awesome skill(shift+d).I also write a bash script to watch the changed of downloading directory(using inotifywait),
You say right ,Linux is free,so feel free.

**Comment by jun7** [comment]
wyeb is made with the intention to belong in scripts though I only use basic functions, So if you find useful actions or env values deserve to add, please tell me it.
thank you.
